log:
  useLogbackConfig: true

wicket:
  contextPath: /ui
  webContentFolder: webcontent

jetty:
  context: /
  connectors:
    - port: 8081
      host: 0.0.0.0
      type: http

simplejavamail:
  accounts:
    test:
      serverAddress: smtp.gmail.com
      serverPort: 587
      username: x@gmail.com
      password: x
      transportStrategy: SMTP_TLS
      debugMode: false

threadpool:
  configs:
    test:
      type: plain
      minThreads: 1
      maxThreads: 2

    trigger:
      type: scheduled
      corePoolSize: 1
